#!/bin/sh
set -xe

# enable experimental cli to use manifest command
export DOCKER_CLI_EXPERIMENTAL=enabled

# include all architectures we build for
ARCHITECTURES="$(cat ./build.arch)"

amend(){
  for arch in $ARCHITECTURES
  do
    echo --amend "$IMAGE_NAME"-"$(echo "$arch" | sed 's#/##')"
  done
  echo
}


for arch in $ARCHITECTURES
do
  if echo "$arch" | grep -q /
  then
    a=$(echo "$arch" | cut -d/ -f1)
    v=$(echo "$arch" | cut -d/ -f2)
    docker manifest annotate "$IMAGE_NAME-$(echo "$arch" | sed 's#/##')" "$IMAGE_NAME-$(echo "$arch" | sed 's#/##')" --os linux --arch "$a" --variant "$v"
  else
    docker manifest annotate "$IMAGE_NAME-$arch" "$IMAGE_NAME-$arch" --os linux --arch "$arch"
  fi
  docker push "$IMAGE_NAME-$(echo "$arch" | sed 's#/##')"
done

docker manifest create "$IMAGE_NAME" $(amend | tr "\n" " ")

for arch in $ARCHITECTURES
do
  if echo "$arch" | grep -q /
  then
    a=$(echo "$arch" | cut -d/ -f1)
    v=$(echo "$arch" | cut -d/ -f2)
    docker manifest annotate "$IMAGE_NAME" "$IMAGE_NAME-$(echo "$arch" | sed 's#/##')" --os linux --arch "$a" --variant "$v"
  else
    docker manifest annotate "$IMAGE_NAME" "$IMAGE_NAME-$arch" --os linux --arch "$arch"
  fi
done

docker manifest push "$IMAGE_NAME"

