#!/bin/sh
set -xe

ARCHITECTURES="$(cat ./build.arch)"

amend(){
  for arch in $ARCHITECTURES
  do
    echo --ammend "$IMAGE_NAME"-"$arch"
  done
  echo
}


for arch in $ARCHITECTURES
do
  docker push "$IMAGE_NAME-$arch"
done

docker manifest create "$IMAGE_NAME" "$(amend | tr "\n" " ")"

